#!/bin/bash

# Set environment variables
export DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
export DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
export DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
export DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}