#!/bin/bash

export DRONE_SERVER_HOST=
echo "\u2714 Set DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}"
export DRONE_RPC_SECRET=
echo "\u2714 Set DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}"
export DRONE_GITHUB_CLIENT_ID=
echo "\u2714 Set DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}"
export DRONE_GITHUB_CLIENT_SECRET=
echo "\u2714 Set DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}"